#Run this with any shuttle file input to get table of raw data
library(stringr)
library(tidyr)
library(dplyr)
library(sqldf)
df1 <- read.delim(file.choose())
df1 <- as.data.frame(df1)
df1 <- df1[grep('00000',df1$D),]
df1 <- as.data.frame(df1)
df1 <- df1 %>% separate(df1, c('Year','Month','Day', 'Time','Blank', 'TrafX_Count','Blank2')) 
df1$Day <- as.numeric(df1$Day)
df1$TrafX_Count <- as.numeric(df1$TrafX_Count)
df1 <- sqldf("select Year, Month, Day, Time, TrafX_Count from df1")
df1$Human_Count <- round((0.3673 * df1$TrafX_Count),0)
df1$Dog_Count <- round((0.4591 * df1$TrafX_Count),0)
df1$Car_Count <- round((0.2959 * df1$TrafX_Count),0)
View(df1)
