---
title: "Tables and Graphs in Markdown"
output: html_document
---

```{r}
library(stringr)
library(tidyr)
library(dplyr)
library(sqldf)
library(lubridate)
library(ggplot2)
library(data.table)
library(tidyverse)
library(forcats)
library(gridExtra)
library(knitr)
library(kableExtra)
```



```{r}
#Load in data frame
df1 <- readRDS('Dog_Park_Data_File_04282022.RDS')
```



```{r}
#Data for attendance by time of day
dfavgtimeofday1 <- sqldf("select Time, Time_of_Day, avg(TrafX_Count), avg(Human_Count), avg(Dog_Count), avg(Car_Count) from df1 group by Time")
dfavgtimeofday1 <- rename(dfavgtimeofday1, 'TrafX_Count' = 'avg(TrafX_Count)')
dfavgtimeofday1<- rename(dfavgtimeofday1, 'Human_Count' = 'avg(Human_Count)')
dfavgtimeofday1 <- rename(dfavgtimeofday1, 'Dog_Count' = 'avg(Dog_Count)')
dfavgtimeofday1 <- rename(dfavgtimeofday1, 'Car_Count' = 'avg(Car_Count)')
dfavgtimeofday <- sqldf("select  Time, Time_of_Day, sum(TrafX_Count), sum(Human_Count), sum(Dog_Count), sum(Car_Count) from dfavgtimeofday1 group by Time_of_Day")
dfavgtimeofday <- rename(dfavgtimeofday, 'TrafX_Count' = 'sum(TrafX_Count)')
dfavgtimeofday <- rename(dfavgtimeofday, 'Human_Count' = 'sum(Human_Count)')
dfavgtimeofday <- rename(dfavgtimeofday, 'Dog_Count' = 'sum(Dog_Count)')
dfavgtimeofday <- rename(dfavgtimeofday, 'Car_Count' = 'sum(Car_Count)')
dfavgtimeofday <- rename(dfavgtimeofday, 'Key' = 'Time_of_Day')
dfavgtimeofday <- dfavgtimeofday[order(dfavgtimeofday$Time),]
#Graph 
dfavgtimeofday_Tall <- dfavgtimeofday %>% gather(key = Count, value = Value, c(Human_Count, Dog_Count, Car_Count))
dfavgtimeofday_graph <- ggplot(dfavgtimeofday_Tall, aes(Count, Value, fill = Key))+
  labs(title = 'Average Attendance By Time of Day', x = 'Type', y = 'Count', color = 'Key:')+
  geom_col(position = 'dodge')
dfavgtimeofday_graph

#5 Number Summary Table 
fivenumbersummarytimeofdaydf <- matrix(c( quantile(dfavgtimeofday$Car_Count), quantile(dfavgtimeofday$Dog_Count), quantile(dfavgtimeofday$Human_Count)), ncol = 3, nrow = 5)
rownames(fivenumbersummarytimeofdaydf) <- c('Min', '25th', 'Median', '75th', 'Max')
colnames(fivenumbersummarytimeofdaydf) <- c('Cars', 'Dogs', 'Humans')
fivenumbersummarytimeofdaytable <- as.table(fivenumbersummarytimeofdaydf)
fivenumbersummarytimeofdaytable
```

```{r}
#Daily data with graphs 
#Group data by date
dfdaily <- sqldf('select Date, Day_Name, Day_Type, sum(TrafX_Count), sum(Human_Count), sum(Dog_Count), sum(Car_Count) from df1 group by Date')
dfdaily <- rename(dfdaily, 'TrafX_Count' = 'sum(TrafX_Count)')
dfdaily <- rename(dfdaily, 'Human_Count' = 'sum(Human_Count)')
dfdaily <- rename(dfdaily, 'Dog_Count' = 'sum(Dog_Count)')
dfdaily <- rename(dfdaily, 'Car_Count' = 'sum(Car_Count)')
#Graph data by date 
daily_graph <- ggplot(dfdaily, aes(x = Date, group = 1))+ 
  labs(title = 'Daily Attendance for Dogs, Humans and Cars', x = 'Date', y = 'Count' , color = 'Key:')+
  geom_line(aes(y = Dog_Count), color = 'green')+
  geom_point(aes(y = Dog_Count, color = 'Dogs'))+
  geom_line(aes(y = Human_Count), color = 'blue')+
  geom_point(aes(y = Human_Count, color = 'Humans'))+ 
  geom_line(aes(y = Car_Count), color = 'red')+
  geom_point(aes(y = Car_Count, color = 'Cars'))+
  scale_y_continuous(breaks = scales::breaks_width(50))
daily_graph

#5 Number Summary Table 
fivenumbersummarydailydf <- matrix(c( quantile(dfdaily$Car_Count), quantile(dfdaily$Dog_Count), quantile(dfdaily$Human_Count)), ncol = 3, nrow = 5)
rownames(fivenumbersummarydailydf) <- c('Min', '25th', 'Median', '75th', 'Max')
colnames(fivenumbersummarydailydf) <- c('Cars', 'Dogs', 'Humans')
fivenumbersummarydailytable <- as.table(fivenumbersummarydailydf)
fivenumbersummarydailytable
```

```{r}
#Attendance by day of week
dfavgdaily <- sqldf('select Date, Day_Name, Day_Type, avg(TrafX_Count), avg(Human_Count), avg(Dog_Count), avg(Car_Count) from dfdaily group by Day_Name')
dfavgdaily <- rename(dfavgdaily, 'TrafX_Count' = 'avg(TrafX_Count)')
dfavgdaily <- rename(dfavgdaily, 'Human_Count' = 'avg(Human_Count)')
dfavgdaily <- rename(dfavgdaily, 'Dog_Count' = 'avg(Dog_Count)')
dfavgdaily <- rename(dfavgdaily, 'Car_Count' = 'avg(Car_Count)')
#Graph
daily_avg_graph <- ggplot(dfavgdaily, aes(x = factor(Day_Name, weekdays(min(Date)+0:6)), group = 1))+
  labs(title = 'Average Dog, Human, and Car Count by the Day of the Week', x = 'Day of Week', y = 'Count', color = 'Key:')+
  geom_line(aes(y = Dog_Count), color = 'green')+
  geom_point(aes(y = Dog_Count, color = 'Dogs'))+
  geom_line(aes(y = Human_Count), color = 'blue')+
  geom_point(aes(y = Human_Count, color = 'Humans'))+
  geom_line(aes(y = Car_Count), color = 'red')+
  geom_point(aes(y = Car_Count, color = 'Cars'))+
  lims(y = c(0,200))
daily_avg_graph

#5 Number Summary Table for graph
fivenumbersummarydailyavgdf <- matrix(c( quantile(dfavgdaily$Car_Count), quantile(dfavgdaily$Dog_Count), quantile(dfavgdaily$Human_Count)), ncol = 3, nrow = 5)
rownames(fivenumbersummarydailyavgdf) <- c('Min', '25th', 'Median', '75th', 'Max')
colnames(fivenumbersummarydailyavgdf) <- c('Cars', 'Dogs', 'Humans')
fivenumbersummarydailyavgtable <- as.table(fivenumbersummarydailyavgdf)
fivenumbersummarydailyavgtable

```

```{r}
#Group by weekend and weekday
dfavgDay_Type <- sqldf("select  Day_Type, avg(TrafX_Count), avg(Human_Count), avg(Dog_Count), avg(Car_Count) from dfavgdaily group by Day_Type")
dfavgDay_Type <- rename(dfavgDay_Type, 'TrafX_Count' = 'avg(TrafX_Count)')
dfavgDay_Type <- rename(dfavgDay_Type, 'Human_Count' = 'avg(Human_Count)')
dfavgDay_Type <- rename(dfavgDay_Type, 'Dog_Count' = 'avg(Dog_Count)')
dfavgDay_Type <- rename(dfavgDay_Type, 'Car_Count' = 'avg(Car_Count)')
dfavgDay_Type <- rename(dfavgDay_Type, 'Key' = 'Day_Type')
#Graph
dfavgDay_Type_Tall <- dfavgDay_Type %>% gather(key = Count, value = Value, c(Human_Count, Dog_Count, Car_Count))
dfavgDay_Type_graph <- ggplot(dfavgDay_Type_Tall, aes(Count, Value, fill = Key))+
  labs(title = 'Average Attendance on Weekends vs Weekdays', x = 'Type', y = 'Count', color = 'Key:')+
  geom_col(position = 'dodge')
dfavgDay_Type_graph

daydf <- sqldf("select sum(Car_Count), sum(Dog_Count), sum(Human_Count), Day_Type from df1 group by Date")
daydf <- rename(daydf, 'Car_Count' = 'sum(Car_Count)')
daydf <- rename(daydf, 'Dog_Count' = 'sum(Dog_Count)')
daydf <- rename(daydf, 'Human_Count' = 'sum(Human_Count)')
Weekenddf <- sqldf("select * from daydf where Day_Type = 'Weekend'")
Weekdaydf <- sqldf("select * from daydf where Day_Type = 'Weekday'")

#5 Number Summary Table for graph
fivenumbersummarydaytypedf <- matrix(c( quantile(dfavgDay_Type_Tall$Value)), ncol = 1, nrow = 5)
rownames(fivenumbersummarydaytypedf) <- c('Min', '25th', 'Median', '75th', 'Max')
colnames(fivenumbersummarydaytypedf) <- c('Count')
fivenumbersummarydaytypetable <- as.table(fivenumbersummarydaytypedf)
fivenumbersummarydaytypetable

#5 Number Summary Table for graph
fivenumbersummarydaytypedf <- matrix(c( quantile(Weekenddf$Car_Count), quantile(Weekenddf$Dog_Count), quantile(Weekenddf$Human_Count), quantile(Weekdaydf$Car_Count), quantile(Weekdaydf$Dog_Count), quantile(Weekdaydf$Human_Count)), ncol = 6, nrow = 5)
rownames(fivenumbersummarydaytypedf) <- c('Min', '25th', 'Median', '75th', 'Max')
colnames(fivenumbersummarydaytypedf) <- c('Cars (Weekend)', 'Dogs (Weekend)', 'Humans (Weekend)', 'Cars (Weekdays)', 'Dogs (Weekdays)', 'Humans (Weekdays)')
fivenumbersummarydaytypetable <- as.table(fivenumbersummarydaytypedf)
fivenumbersummarydaytypetable
```

```{r}
#Create new data frame just for specific columns needed for next graphs
df2 <- df1
df2$Date_Time_of_Day <- paste(df2$Date, df2$Time_of_Day)
#Group by time of day and weekend or weekday
dfavgDay_Type_Time_of_Day1 <- sqldf("select Day_Type_Time_of_Day, Time_of_Day, Date_Time_of_Day, Date, Time, Day_Type, sum(TrafX_Count), sum(Human_Count), sum(Dog_Count), sum(Car_Count) from df2 group by Date_Time_of_Day")
dfavgDay_Type_Time_of_Day1 <- rename(dfavgDay_Type_Time_of_Day1, 'TrafX_Count' = 'sum(TrafX_Count)')
dfavgDay_Type_Time_of_Day1 <- rename(dfavgDay_Type_Time_of_Day1, 'Human_Count' = 'sum(Human_Count)')
dfavgDay_Type_Time_of_Day1 <- rename(dfavgDay_Type_Time_of_Day1, 'Dog_Count' = 'sum(Dog_Count)')
dfavgDay_Type_Time_of_Day1 <- rename(dfavgDay_Type_Time_of_Day1, 'Car_Count' = 'sum(Car_Count)')
dfavgDay_Type_Time_of_Day <- sqldf("select Time_of_Day, Time, Day_Type, avg(TrafX_Count), avg(Human_Count), avg(Dog_Count), avg(Car_Count) from dfavgDay_Type_Time_of_Day1 group by Day_Type_Time_of_Day")
dfavgDay_Type_Time_of_Day <- rename(dfavgDay_Type_Time_of_Day, 'TrafX_Count' = 'avg(TrafX_Count)')
dfavgDay_Type_Time_of_Day <- rename(dfavgDay_Type_Time_of_Day, 'Human_Count' = 'avg(Human_Count)')
dfavgDay_Type_Time_of_Day <- rename(dfavgDay_Type_Time_of_Day, 'Dog_Count' = 'avg(Dog_Count)')
dfavgDay_Type_Time_of_Day <- rename(dfavgDay_Type_Time_of_Day, 'Car_Count' = 'avg(Car_Count)')
#Graph for Weekends
dfavgDay_Type_Time_of_Day_Weekend <-sqldf("select Time_of_Day, Time, Day_Type, TrafX_Count, Human_Count, Dog_Count, Car_Count from dfavgDay_Type_Time_of_Day where Day_Type == 'Weekend'")
dfavgDay_Type_Time_of_Day_Weekend <- rename(dfavgDay_Type_Time_of_Day_Weekend, 'Key' = 'Time_of_Day')
dfavgDay_Type_Time_of_Day_Weekend_Tall <- dfavgDay_Type_Time_of_Day_Weekend %>% gather(key = Count, value = Value, c(Human_Count, Dog_Count, Car_Count))
dfavgDay_Type_Time_of_Day_Weekend_Tall_graph <- ggplot(dfavgDay_Type_Time_of_Day_Weekend_Tall, aes(Count, Value, fill = Key))+
  labs(title = 'Average Attendance on Weekends Per Time of Day', x = 'Time', y = 'Count', color = 'Key:')+
  geom_col(position = 'dodge')+
  lims(y = c(0,100))
dfavgDay_Type_Time_of_Day_Weekend_Tall_graph
#Graph for Weekdays 
dfavgDay_Type_Time_of_Day_Weekday <-sqldf("select Time_of_Day, Time, Day_Type, TrafX_Count, Human_Count, Dog_Count, Car_Count from dfavgDay_Type_Time_of_Day where Day_Type == 'Weekday'")
dfavgDay_Type_Time_of_Day_Weekday <- rename(dfavgDay_Type_Time_of_Day_Weekday, 'Key' = 'Time_of_Day')
dfavgDay_Type_Time_of_Day_Weekday_Tall <- dfavgDay_Type_Time_of_Day_Weekday %>% gather(key = Count, value = Value, c(Human_Count, Dog_Count, Car_Count))
dfavgDay_Type_Time_of_Day_Weekday_Tall_graph <- ggplot(dfavgDay_Type_Time_of_Day_Weekday_Tall, aes(Count, Value, fill = Key))+
  labs(title = 'Average Attendance on Weekdays Per Time of Day', x = 'Time', y = 'Count', color = 'Key:')+
  geom_col(position = 'dodge')+
  lims(y = c(0,100))
dfavgDay_Type_Time_of_Day_Weekday_Tall_graph
grid.arrange(dfavgDay_Type_Time_of_Day_Weekend_Tall_graph, dfavgDay_Type_Time_of_Day_Weekday_Tall_graph, ncol=2)

```


```{r}
#Attendance for the week 
attendance_by_week <- sqldf("select Date, Week, sum(TrafX_Count), sum(Human_Count), sum(Dog_Count), sum(Car_Count) from df1 group by Week")
attendance_by_week <- rename(attendance_by_week, 'TrafX_Count' = 'sum(TrafX_Count)')
attendance_by_week <- rename(attendance_by_week, 'Human_Count' = 'sum(Human_Count)')
attendance_by_week <- rename(attendance_by_week, 'Dog_Count' = 'sum(Dog_Count)')
attendance_by_week <- rename(attendance_by_week, 'Car_Count' = 'sum(Car_Count)')
#Graph
attendance_by_week_graph <- ggplot(attendance_by_week, aes(x = Date, group = 1))+
  labs(title = 'Total Attendance by the Week', x = 'Week', y = 'Total Attendance', color = 'Key:')+
  geom_line(aes(y = Dog_Count), color = 'green')+
  geom_point(aes(y = Dog_Count, color = 'Dogs'))+
  geom_line(aes(y = Human_Count), color = 'blue')+
  geom_point(aes(y = Human_Count, color = 'Humans'))+ 
  geom_line(aes(y = Car_Count), color = 'red')+
  geom_point(aes(y = Car_Count, color = 'Cars'))
attendance_by_week_graph

#5 Number Summary Table for graph
fivenumbersummaryweeklydf <- matrix(c( quantile(attendance_by_week$Car_Count), quantile(attendance_by_week$Dog_Count), quantile(attendance_by_week$Human_Count)), ncol = 3, nrow = 5)
rownames(fivenumbersummaryweeklydf) <- c('Min', '25th', 'Median', '75th', 'Max')
colnames(fivenumbersummaryweeklydf) <- c('Cars', 'Dogs', 'Humans')
fivenumbersummaryweeklytable <- as.table(fivenumbersummaryweeklydf)
fivenumbersummaryweeklytable
```

```{r}
#Attendance by Month
attendance_by_month <- sqldf("select Date, Month, sum(TrafX_Count), sum(Human_Count), sum(Dog_Count), sum(Car_Count) from df1 group by Month")
attendance_by_month <- rename(attendance_by_month, 'TrafX_Count' = 'sum(TrafX_Count)')
attendance_by_month <- rename(attendance_by_month, 'Human_Count' = 'sum(Human_Count)')
attendance_by_month <- rename(attendance_by_month, 'Dog_Count' = 'sum(Dog_Count)')
attendance_by_month <- rename(attendance_by_month, 'Car_Count' = 'sum(Car_Count)')
#Graph 
attendance_by_month_graph <- ggplot(attendance_by_month, aes(Month, group = 1))+
  labs(title = 'Total Attendance by the Month', x = 'Month', y = 'Total Attendance', color = 'Key:')+
  geom_line(aes(y = Dog_Count), color = 'green')+
  geom_point(aes(y = Dog_Count, color = 'Dogs'))+
  geom_line(aes(y = Human_Count), color = 'blue')+
  geom_point(aes(y = Human_Count, color = 'Humans'))+ 
  geom_line(aes(y = Car_Count), color = 'red')+
  geom_point(aes(y = Car_Count, color = 'Cars'))
attendance_by_month_graph

#5 Number Summary Table for graph
fivenumbersummarymonthlydf <- matrix(c( quantile(attendance_by_month$Car_Count), quantile(attendance_by_month$Dog_Count), quantile(attendance_by_month$Human_Count)), ncol = 3, nrow = 5)
rownames(fivenumbersummarymonthlydf) <- c('Min', '25th', 'Median', '75th', 'Max')
colnames(fivenumbersummarymonthlydf) <- c('Cars', 'Dogs', 'Humans')
fivenumbersummarymonthlytable <- as.table(fivenumbersummarymonthlydf)
fivenumbersummarymonthlytable
```


```{r}
#Daily Attendance by Temperature
#This graph is based on average temp of the day.  It is not a graph of average attendance at a specific temperature. 

dfdailyweather <- sqldf("select Date, avg(Temp), sum(Precipitation), avg(Wind), sum(Human_Count), sum(Dog_Count), sum(Car_Count) from df1 group by Date")
dfdailyweather <- rename(dfdailyweather, 'Temp' = 'avg(Temp)')
dfdailyweather <- rename(dfdailyweather, 'Precipitation' = 'sum(Precipitation)')
dfdailyweather <- rename(dfdailyweather, 'Wind' = 'avg(Wind)')
dfdailyweather <- rename(dfdailyweather, 'Human_Count' = 'sum(Human_Count)')
dfdailyweather <- rename(dfdailyweather, 'Dog_Count' = 'sum(Dog_Count)')
dfdailyweather <- rename(dfdailyweather, 'Car_Count' = 'sum(Car_Count)')
dfdailyweather$Temp_Range <- with(dfdailyweather, ifelse(Temp <= 20, '1- (< 20 Degrees)', ifelse(Temp <= 40, '2- (20-40 Degrees)', ifelse(Temp <= 60, '3- (40-60 Degrees)', ifelse(Temp <= 80, '4- (60-80 Degrees)', ifelse(Temp <= 10000, '5- (> 80 Degrees)'))))))
dfdailyweather$Precipitation_Range <- with(dfdailyweather, ifelse(Precipitation <= 0.0000001, '1- No Precipitation', ifelse(Precipitation <= 0.25, '2- Light Precipitation', ifelse(Precipitation <= 0.5, '3- Consistent Precipitation', ifelse(Precipitation <= 0.75, '4- Consisten Heavy Precipitation', ifelse(Precipitation <= 80, '5- Storm Precipitation'))))))
dfdailyweather$Wind_Range <- with(dfdailyweather, ifelse(Wind <= 1, '1- No Wind', ifelse(Wind <= 6, '2- Light Winds', ifelse(Wind <= 15, '3- Moderate Winds', ifelse(Wind <= 30, '4- Strong Winds', ifelse(Wind <= 50, '5- Storm Winds', ifelse(Wind <= 1000, '6- Violent Winds')))))))
dfdailytemp <- sqldf("select Temp_Range, avg(Temp), avg(Human_Count), avg(Dog_Count), avg(Car_Count) from dfdailyweather group by Temp_Range")
dfdailytemp <- rename(dfdailytemp, 'Temp' = 'avg(Temp)')
dfdailytemp <- rename(dfdailytemp, 'Human_Count' = 'avg(Human_Count)')
dfdailytemp <- rename(dfdailytemp, 'Dog_Count' = 'avg(Dog_Count)')
dfdailytemp <- rename(dfdailytemp, 'Car_Count' = 'avg(Car_Count)')
dfdailytemp <- rename(dfdailytemp, 'Key' = 'Temp_Range')
attendancebytempgraph_tall <- dfdailytemp %>% gather(key = Count, value = Value, c(Human_Count, Dog_Count, Car_Count))
attendancebytempgraph <- ggplot(attendancebytempgraph_tall, aes(Count, Value, fill = Key))+
  labs(title = 'Attendance by Average Daily Temperature', x = 'Type', y = 'Attendance', color = 'Key:')+
  geom_col(position = 'dodge')
attendancebytempgraph
```



```{r}
# Daily Attendance by Precipitation 
dfdailyprecipitation <- sqldf("select Precipitation_Range, avg(Precipitation), avg(Human_Count), avg(Dog_Count), avg(Car_Count) from dfdailyweather group by Precipitation_Range")
dfdailyprecipitation <- rename(dfdailyprecipitation, 'Precipitation' = 'avg(Precipitation)')
dfdailyprecipitation <- rename(dfdailyprecipitation, 'Human_Count' = 'avg(Human_Count)')
dfdailyprecipitation <- rename(dfdailyprecipitation, 'Dog_Count' = 'avg(Dog_Count)')
dfdailyprecipitation <- rename(dfdailyprecipitation, 'Car_Count' = 'avg(Car_Count)')
dfdailyprecipitation <- rename(dfdailyprecipitation, 'Key' = 'Precipitation_Range')
attendancebyprecipitationgraph_tall <- dfdailyprecipitation %>% gather(key = Count, value = Value, c(Human_Count, Dog_Count, Car_Count))
attendancebyprecipitationgraph <- ggplot(attendancebyprecipitationgraph_tall, aes(Count, Value, fill = Key))+
  labs(title = 'Attendance by Average Daily Precipitation-Measurements from Weather Insurance Agency', x = 'Type', y = 'Attendance', color = 'Key:')+
  geom_col(position = 'dodge')
attendancebyprecipitationgraph
```


```{r}
# Daily Attendance by Wind
dfdailywind <- sqldf("select Wind_Range, avg(Wind), avg(Human_Count), avg(Dog_Count), avg(Car_Count) from dfdailyweather group by Wind_Range")
dfdailywind <- rename(dfdailywind, 'Wind' = 'avg(Wind)')
dfdailywind <- rename(dfdailywind, 'Human_Count' = 'avg(Human_Count)')
dfdailywind <- rename(dfdailywind, 'Dog_Count' = 'avg(Dog_Count)')
dfdailywind <- rename(dfdailywind, 'Car_Count' = 'avg(Car_Count)')
dfdailywind <- rename(dfdailywind, 'Key' = 'Wind_Range')
attendancebywindgraph_tall <- dfdailywind %>% gather(key = Count, value = Value, c(Human_Count, Dog_Count, Car_Count))
attendancebywindgraph <- ggplot(attendancebywindgraph_tall, aes(Count, Value, fill = Key))+
  labs(title = 'Attendance by Average Daily Wind-Measurements from Beaufort Wind Scale', x = 'Type', y = 'Attendance', color = 'Key:')+
  geom_col(position = 'dodge')
attendancebywindgraph
```









